media:
  input: static/img
  output: /img

content:
  - name: homepage
    label: Homepage
    path: data/homepage.yml
    type: file
    format: yaml
    fields:
      - name: head
        type: object
        fields:
          - name: title
            label: Website title
            type: string
          - name: img_start
            label: Start Image
            type: image
          - name: img_nav
            label: Navigation Image
            type: image
          
      - name: about
        type: object
        fields:
          - name: enable
            label: Enable Section
            type: boolean
          - name: title
            label: Section Title
            type: string
          - name: content
            label: About Content
            type: rich-text
          - name: image
            type: object
            fields:
              - name: alt
                label: Image Description
                type: string
              - name: x
                label: Image
                type: image
                options:
                  path: src/media/screenshots
              - name: x2
                label: High Resolution Image
                type: image
                options:
                  path: src/media/screenshots
      - name: demo
        type: object
        fields:
          - name: title
            label: Demo Title
            type: string
      - name: contact
        type: object
        fields:
          - name: email
            label: Contact Email
            type: string
          