media:
  input: static/img
  output: /img

content:
  - name: homepage
    label: Homepage
    path: data/homepage.yml
    type: file
    format: yaml
    fields:
      - name: head
        type: object
        fields:
        - name: title
          label: Website title
          type: string